" vim configuration ( for navi )
" this file is stored at $HOME/.vimrc
set number
set mouse=a
set hlsearch
set incsearch 
set wrap
set autoindent
set cursorline 
set cursorlineopt=number
filetype indent on
syntax enable
